In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [8]:
np.arange(0,2,21)

array([0])

In [9]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.zeros(1)

array([0.])

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(1,6,25)

array([1.        , 1.20833333, 1.41666667, 1.625     , 1.83333333,
       2.04166667, 2.25      , 2.45833333, 2.66666667, 2.875     ,
       3.08333333, 3.29166667, 3.5       , 3.70833333, 3.91666667,
       4.125     , 4.33333333, 4.54166667, 4.75      , 4.95833333,
       5.16666667, 5.375     , 5.58333333, 5.79166667, 6.        ])

In [18]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.array(4)

array(4)

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(1)

array([0.33826315])

In [23]:
np.random.rand(2)

array([0.12375387, 0.1124188 ])

In [24]:
np.random.rand(3)

array([0.3286647 , 0.75755108, 0.94065596])

In [25]:
np.random.rand(5,5)

array([[0.33810507, 0.67854269, 0.0622393 , 0.68083161, 0.71977791],
       [0.85379491, 0.6023799 , 0.83271172, 0.34833326, 0.33386982],
       [0.90369987, 0.11437913, 0.04311723, 0.13884701, 0.05605281],
       [0.27146734, 0.23873856, 0.48503165, 0.31462887, 0.27873021],
       [0.10503599, 0.55095878, 0.65706618, 0.69644795, 0.97748796]])

In [26]:
np.random.randn(1)

array([-0.47267575])

In [27]:
np.random.randn(2)

array([ 0.29507644, -0.92434462])

In [28]:
np.random.randn(3,3)

array([[-1.45611074,  1.47171904, -0.86301709],
       [-0.5645118 , -0.81246042, -0.85864908],
       [-1.56736984, -0.08920026, -0.2138149 ]])

In [29]:
np.random.randint(1,50)

32

In [30]:
np.random.randint(1,20)

9

In [31]:
np.random.randint(1,10)

6

In [32]:
np.random.randint(1,4)

1

In [33]:
np.random.randint(1,6)

3

In [34]:
np.random.randint(1,100,10)

array([ 1, 25, 26, 66, 63, 93, 28, 21, 94, 55])

In [35]:
arr=np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr=np.random.randint(0,25,10)

In [38]:
ranarr

array([24, 10, 20, 10, 24, 19, 23,  2,  8, 23])

In [39]:
ranarr.max()

24

In [40]:
ranarr.min()

2

In [41]:
ranarr.argmax()

0

In [42]:
ranarr.argmin()

7

In [43]:
arr.shape

(25,)

In [44]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
arr.shape

(25,)

In [46]:
v=np.array([1,2,3])
print(v)

[1 2 3]


In [47]:
v.shape

(3,)

In [48]:
list(range(0,25))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24]

In [49]:
print(list)

<class 'list'>


In [50]:
a=np.array([[1,2,3],[2,3,4]])
a.shape

(2, 3)

In [51]:
b=np.array([[1,2,3],[2,3,4],['a','b','c']])

In [52]:
b.shape

(3, 3)

In [53]:
import numpy as np


In [54]:
arr=np.arange(0,11)

In [55]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr[8]

8

In [57]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [12]:
import numpy as np


In [13]:
arr=np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr[8]

8

In [16]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [17]:
arr[0:5]=25

In [18]:
arr

array([25, 25, 25, 25, 25,  5,  6,  7,  8,  9, 10])

In [19]:
slice_of_arr=arr[0:6]

In [20]:
slice_of_arr

array([25, 25, 25, 25, 25,  5])

In [21]:
slice_of_arr[:]=99
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [23]:
slice_of_arr[1:]

array([99, 99, 99, 99, 99])

In [32]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [33]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [34]:
arr_2d[1]

array([20, 25, 30])

In [35]:
arr_2d[1][1]

25

In [36]:
arr_2d[0][1]

10

In [37]:
arr_2d[2][2]

45

In [38]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [39]:
arr_2d[2:]

array([[35, 40, 45]])

In [40]:
arr_2d[2]

array([35, 40, 45])

In [41]:
arr_2d[1][2]

30

In [45]:
arr2d=np.zeros((10,10))

In [46]:
arr_length=arr2d.shape[1]

In [47]:
for i in range(arr_length):
    arr2d[i]=i

In [48]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [49]:
arr2d=np.ones((10,10))

In [50]:
arr_length=arr2d.shape[1]

In [52]:
for i in range(arr_length):
    arr2d[i]=i
    

In [53]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr=np.arange(1,11)

In [54]:
arr>4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [55]:
bool_arr=arr>4

In [56]:
arr[bool_arr]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr<2

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [58]:
x=2

In [59]:
arr[arr>x]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [61]:
arr>x

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])